Neos:
  ContentRepositoryRegistry:
    presets:
      default:

        commandHooks:
          'Jonnitto.PrettyEmbedHelper:AssetDownloadCommandHook':
            factoryObjectName: Jonnitto\PrettyEmbedHelper\CommandHook\AssetDownloadCommandHookFactory
